### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by nesl247** [dracula/emacs#10]
Hey everyone,

We're looking for a maintainer for Emacs. I tried to reach out to @film42 as he was the maintainer before the organization move, but have not been able to get a hold of him over a month, so we're opening up the maintainer position.

Thanks.
- Dracula Theme Team

**Comment by film42** [comment]
Sorry for the lack of responsiveness. I have time to review PRs but probably won't have time to create PRs out of open issues. P.S. Thanks for pinging me on this issue.

**Comment by gilbertw1** [comment]
Hey, I'm more than happy to help out if you need it. I've been using this theme as my daily driver and plan to actively contribute to it for the foreseeable future.

**Comment by 0zguner** [comment]
Hey, I can work on js2-mode ✌️

**Comment by nesl247** [comment]
@film42 How would you like to proceed? We have a few people here interesting in helping out. We can certainly have multiple maintainers if you'd like to remain onboard, or if you no longer wish to be listed as one, we can always swap you out.

Let me know what you think.

**Comment by film42** [comment]
This project is pretty low maintenance, so I'd be happy to review things. I'm happy to remain a maintainer of this theme for now :). I think if @gilbertw1 and @mzgnr want to start contributing, then that additional help would be great!
