### ISSUE TITLE
Background not loaded for GUI Emacs when started from terminal

### ISSUE THREAD

**Issue by Abizern** [dracula/emacs#21]
<img width="576" alt="screen shot 2017-03-03 at 20 03 43" src="https://cloud.githubusercontent.com/assets/6902/23567089/8d2f2d68-004c-11e7-905f-77a46716b390.png">

I'm running on a Mac

I run emacs starting with:

    emacs --daemon

and then either load a GUI client with:

    emacsclient -nc

or in the terminal with:

    emacsclient -t

In the case of the terminal session everything looks fine.

In the case of the GUI client, I have no background colour.

When I launch the emacs GUI client directly, everything is set correctly - there is a dark background colour.

From what I can see this is introduced by #19, because when I comment out the changes I get the expected behaviour.

I tried to fix this by adding a hook to 'after-make-frame-functions, but I couldn't get it to work.

**Comment by film42** [comment]
@benjamreynolds @apierz maybe we should change the terminal background to black to avoid this?

**Comment by benreyn** [comment]
Yeah, I think that would be a good temporary fix until I can dig a bit deeper into how other themes are constructed to avoid issues like this. (or, as some of my research suggests, it may not be possible to get consistent colors across terminal and gui sessions)

I'll submit a quick PR for this, which will basically looked like the closed #15

**Comment by film42** [comment]
Thanks for the patch @benjamreynolds !

@Abizern , just released a new version that sets the background to black when using emacs in a terminal. It's not perfect, but we're working on a better long-term solution. Thanks! ❤️

**Comment by Abizern** [comment]
Thank you.
