### ISSUE TITLE
give some emacs Haskell love too

### ISSUE THREAD

**Issue by CarstenKoenig** [dracula/emacs#27]
There was a recent update to the vs.code theme that really made Haskell code much more beautiful:

![vscode](https://user-images.githubusercontent.com/1927108/26974499-ed7249f0-4d1b-11e7-9b6f-fe920400caac.png)

it would be so nice if Emacs could receive the same love:

![draculaemacs](https://user-images.githubusercontent.com/1927108/26974515-fc8fee9c-4d1b-11e7-8b99-df550d91bcc9.png)

from what I see it's mainly the operators and number literals that makes the difference.

**Comment by milouse** [comment]
@CarstenKoenig can you confirm if my last commits do the job for you?

As far as I know, there is now way in emacs to propertize number or operator. At least by default, maybe you should try to contact the haskell-mode author?

**Comment by milouse** [comment]
No feedbacks in a while, I assume it's ok then.
