### ISSUE TITLE
terminal colors for emacs

### ISSUE THREAD

**Issue by octavz** [dracula/emacs#32]
![1_005](https://user-images.githubusercontent.com/23629302/34881374-1a789d3c-f7bc-11e7-8f72-ae5055b51174.png)

I am using termite and on the left there is `emacs` on the rigth `emacs -nw`. 
As a reference vim-dracula works fine in terminal, the terminal itself renders the colors ok, only emacs doesn't.

Also tried `gnome-terminal`, `xterm`,`terminator` to no avail

Can anyone point me in the right direction?

Thank you

**Comment by scturtle** [comment]
Comment out the background part in default:
```emacs
   `(default (;;(((type nil)) (:background "#000000" :foreground ,fg1))
              (,class (:background ,bg1 :foreground ,fg1))))
```

**Comment by owlas** [comment]
The reason is that in a terminal environment the background is set to black. I just patched this in my local version but I guess this won't work in a TTY where only 16 colors are available.

See line [`./dracula-theme.el#L24`](https://github.com/dracula/emacs/blob/1f649824d996b1ecdcc5980210b774f0cb950e9a/dracula-theme.el#L24)

I'm not sure what the most preferable behaviour is to be honest but I'm happy to have my colours back!

**Comment by razum2um** [comment]
Same issue here:
<img width="1680" alt="Screenshot 2019-09-12 at 14 33 37" src="https://user-images.githubusercontent.com/122018/64763629-9dab2700-d56a-11e9-87ef-9dfb689c1991.png">
both are `-nw` (left: master, right (same as gui):  https://github.com/razum2um/emacs/commit/3e5b39a611261a2d2c86cf0df392399c0c223204)

I think black terminal bg is intentional because they don't rely on underlying terminal bg color hence `#000`

**Comment by avatar-lavventura** [comment]
I am having the same issue after doing `export TERM=xterm-256color`, background color is all black.

**Comment by avatar-lavventura** [comment]
Adding following line fixed my solution but on my iTerm I have dracula's theme as well. (https://stackoverflow.com/a/20233611/2402577)

```
(defun on-after-init ()
  (unless (display-graphic-p (selected-frame))
    (set-face-background 'default "unspecified-bg" (selected-frame))))

(add-hook 'window-setup-hook 'on-after-init)
```

**Comment by milouse** [comment]
I try to move on this one with my last commit. Can you all upgrade and see if it's better or worse? Thank you very much.

**Comment by milouse** [comment]
To continue the discussion, the blue colors which appears sometimes (see #2) seems to be `color-17` as seen by `M-x list-colors-display`. I cannot find any relation to that.

**Comment by avatar-lavventura** [comment]
Thanks @milouse. Your recommended guide solved my problem:

I commented out following line:

```
(dracula-bg      "#282a36" "#000000") ;
```

--- 

And added this line in between `(deftheme dracula)` and `(let ((colors '(...` 

```
(if (display-graphic-p) (setq dracula-bg "#282a36") (setq dracula-bg nil))
```

**Comment by avatar-lavventura** [comment]
This approcach messes up some other coloring stuff on highlighting @milouse

**Comment by milouse** [comment]
@avatar-lavventura you should not have to add anything else to test my commit. Or you don't use melpa package?

Can you precise your last message (what do you mean by "mess up", can you take a screenshot? Thank you very much.

**Comment by avatar-lavventura** [comment]
I have downloaded dracula theme into `$HOME/.emacs.d/themes/dracula-theme.el` and made following changes:

```
(require 'cl-lib)
(deftheme dracula)

(if (display-graphic-p) (setq dracula-bg "#282a36") (setq dracula-bg nil)) ;; <= added line

;; Assigment form: VARIABLE COLOR [TTY-COLOR]
(let ((colors '(;; Upstream theme color
                ;(dracula-bg      "#282a36" "#000000") ; official background ;; <= commented out
```

<img width="660" alt="Screen Shot 2020-02-10 at 13 52 16" src="https://user-images.githubusercontent.com/18537398/74143819-8f8e2f00-4c0c-11ea-9208-2d400e496b08.png">

------------------

Original

<img width="657" alt="Screen Shot 2020-02-10 at 13 53 13" src="https://user-images.githubusercontent.com/18537398/74143877-b0568480-4c0c-11ea-84c8-610b814ecc47.png">

**Comment by milouse** [comment]
Why don't you just replace the `"#000000"` by a `nil` ? That way you don't have to add your `if` line or comment anything. Try to download the last commited version (which already contains the fix) because you may lack some other changes done in the meantime.

**Comment by avatar-lavventura** [comment]
I have used the latest commit but still has the same issue. When highlighting, it keeps the original color of strings instead of making them black, hence on yellow background its very difficult to see them.

`(region :background ,dracula-yellow :foreground ,dracula-bg :extend t)` => should be =>
`(region :background ,dracula-yellow :foreground ,"#000000" :extend t)`

**Comment by milouse** [comment]
I just commit a little rewrite of the base colors, following [doom-dracula-theme](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-dracula-theme.el) colors. It should fix this long running problem about terminal. Can you all take time to test [this version](https://github.com/dracula/emacs/blob/ed-test-term-colors/dracula-theme.el)?

**Comment by avatar-lavventura** [comment]
Comments are unreadable, comments could be little bit more live color like green: 
<img width="478" alt="Screen Shot 2020-02-11 at 13 22 16" src="https://user-images.githubusercontent.com/18537398/74228462-874bf780-4cd1-11ea-94c1-e817af3ba6f1.png">

------

When I apply `M-x - rgrep` also highlighted words on the opened second screen is not that readable with the colors.

Example: 

<img width="1014" alt="Screen Shot 2020-02-11 at 15 12 29" src="https://user-images.githubusercontent.com/18537398/74235841-f67d1800-4ce0-11ea-8c32-ab44c446d77d.png">

**Comment by milouse** [comment]
Hi, can you try to [download it again](https://github.com/dracula/emacs/blob/ed-test-term-colors/dracula-theme.el) and try my last modifications?

I didn't have the same behavior for the rgrep output. Can you precise your emacs version and, if possible, when you are in the rgrep output buffer, can you place your cursor on one of the matched item and enter `M-x describe-face` and tell me the result of the command? Thank you.

**Comment by avatar-lavventura** [comment]
When you `isearch` a word it highlights other found ones with black background so its hard to detect see all the found words on the `isearch`.

For example I am search `import` other find string's background is black, which is hard to detect.

<img width="527" alt="Screen Shot 2020-02-12 at 14 46 34" src="https://user-images.githubusercontent.com/18537398/74332310-83d67000-4da6-11ea-9373-81719d6c3ac1.png">

---

Typing color is more grayish, I thinkg it was white on the previous setup, which was much better in my opinion. 

Original:
<img width="578" alt="Screen Shot 2020-02-12 at 14 20 05" src="https://user-images.githubusercontent.com/18537398/74330713-386e9280-4da3-11ea-8bce-cd6b3c81be03.png">

New commit:
<img width="610" alt="Screen Shot 2020-02-12 at 14 20 26" src="https://user-images.githubusercontent.com/18537398/74330730-41f7fa80-4da3-11ea-9b4b-0ac222b737fd.png">

**Comment by milouse** [comment]
Hi, I just give it another shot? Do you mind [test it again](https://raw.githubusercontent.com/dracula/emacs/9a57bc5512dad37ac38d890e28e6a4b20ccc10b9/dracula-theme.el) ?

I change the fg color to bright white and try to have a lighter background for lazy-highlight items. But we are very limited on terminal colors, thus I don't think I'll be able to do better here.

**Comment by avatar-lavventura** [comment]
Its much better, but only comment color could be different color since its so close to background color.

**Comment by milouse** [comment]
Is it better [now](https://raw.githubusercontent.com/dracula/emacs/ed-test-term-colors/dracula-theme.el)?

**Comment by avatar-lavventura** [comment]
Yes, thank you @milouse
