### ISSUE TITLE
font-lock-variable-name-face is the same as default

### ISSUE THREAD

**Issue by finalpatch** [dracula/emacs#34]
they are both #f8f8f2. not sure if this is intended. 

IMO,  we could add something like a :bold t and drop the foreground property in this face, as everything is automatically inherited from 'default'.  This way the overall color balance won't change too much but we could have variable names stand out a little bit.

**Comment by milouse** [comment]
I begin to look at it but don't succeeded to have the bold face working. I'll dig it a little more. But I'm not sure it's a real problem.

**Comment by milouse** [comment]
I finally got a proof for that, shown in the following capture.

![Capture du 2019-10-28 22-00-18](https://user-images.githubusercontent.com/349239/67717636-684d8200-f9ce-11e9-83bf-28752559102a.png)

1. shows python code
2. shows ruby code
3. shows lisp code

I'm not sure it's a good idea to propertize variables as bold. As you can see, only variable affectation are propertized. It seems (to me at least) to not add better readability. What do you think?

**Comment by finalpatch** [comment]
Hi thanks for looking into this.  I was just trying to point out that in this color theme variable names are not highlighted.  Since font-lock-variable-name-face is a standard font lock face,  I think it is probably intended to be highlighted.  If "bold" doesn't look good, I'm sure you can come up with something better (I suggested "bold" in the original report only because I don't want to change it too much no knowing better).

**Comment by milouse** [comment]
~~Personnally, I like it simple and don't see any added value to propertize variable otherwise. Thus I'll leave it open until someone came with a good idea.~~

I change my mind. I'll push my change and we'll see if it opens other opinion on that (you got one +1 after all :) )
