### ISSUE TITLE
Ugly background color around dots in whitespace-mode

### ISSUE THREAD

**Issue by in-in** [dracula/emacs#35]
![5acdf](https://user-images.githubusercontent.com/8797432/39113959-009b1718-46e6-11e8-92f0-66a9482dee91.png)

Ubuntu 16.04
Emacs 25.3.2
Dracula-theme-1.2.5

**Comment by ghost** [comment]
that's also used as background of submodes when using `mmm-mode` :disappointed:

**Comment by milouse** [comment]
The theme lacks of the faces declared in the whitespace mode. There are a lot of them, but it should be easy to add them even for a newcommer.

That said, I don't know what is mmm-mode and it may be a new issue as faces are never shared between packages.
