### ISSUE TITLE
powerline background uses highlight foreground-color

### ISSUE THREAD

**Issue by eigengrau** [dracula/emacs#38]
I notice that with 3054c3d, we start using a highlight color for parts of the powerline background, which looks jarring and distracting. 3054c3d also removes the visual separation between different powerline segments in the background. I’m not quite sure what the perceived issue with powerline colors before that commit was, but perhaps there’s a better way of addressing it?

Now:
![now](https://user-images.githubusercontent.com/4939947/40161900-6ead566a-59b2-11e8-84dc-d2e635579d71.png)

Before:
![before](https://user-images.githubusercontent.com/4939947/40161899-6e8f9c38-59b2-11e8-96be-460e7f27d59e.png)

**Comment by milouse** [comment]
@eigengrau does my last commit fix your problem?

**Comment by milouse** [comment]
No feedbacks in a while, I assume it's ok then.
