### ISSUE TITLE
neotree file color should be brighter

### ISSUE THREAD

**Issue by royxue** [dracula/emacs#42]
![image](https://user-images.githubusercontent.com/4725561/42025815-1a108b06-7af8-11e8-97d0-60e1454bf21f.png)

The color for neotree files name are too close to the background, which is hard to identify them

**Comment by milouse** [comment]
I think you are speaking about this package https://github.com/jaypei/emacs-neotree

[Faces are declared here](https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el#L408) and should be investigated. 

This bug is an easy one for beginner.
