### ISSUE TITLE
Not found dracula-theme-1.2.0.el into MELPA stable

### ISSUE THREAD

**Issue by leandropincini** [dracula/emacs#6]
Hi,

First of all, thanks for the dracula-theme for emacs...

I'm trying to use dracula-theme for emacs and, ok... it isn't in MELPA stable yet...
My question is, anybody have any idea about how long will it take?

TIA

**Comment by shuxiao9058** [comment]
I have the same question too.

**Comment by film42** [comment]
Looks like it's in MELPA stable: http://stable.melpa.org/#/dracula-theme
