### ISSUE TITLE
Adding faces for lsp-ui

### ISSUE THREAD

**Issue by shpark** [dracula/emacs#64]
![Screenshot from 2020-05-07 17-24-51](https://user-images.githubusercontent.com/61111279/81271909-addabe00-9087-11ea-9b42-93a314a30b7c.png)

Some faces for lsp-ui (say 'lsp-ui-peek-highlight') are not defined, so IMO it doesn't look good.

It would be great if dracula provides some faces for lsp-mode users

**Comment by milouse** [comment]
I think you refer to https://github.com/emacs-lsp/lsp-mode, which I don't know at all. Can you annotate your screenshot to let me better understand where is the missing face, what is its purpose…

Don't hesitate to share several screenshot to help me figure out how the whole thing works.

**Comment by milouse** [comment]
~~I find all face declaration in [that file](https://github.com/emacs-lsp/lsp-mode/blob/51d960f742e8ccd33f6fd2d9836bf9274413ff10/lsp-mode.el). What is strange is that they all inherit from default faces, thus it should be already ok.~~

Wow ok, in fact you are speaking about https://github.com/emacs-lsp/lsp-ui, which hardcode a lot of new faces… It won't be easy to check that without using it.

If any user of it wants to contribute, don't hesitate to submit a PR :)
