### ISSUE TITLE
Unable to load color "unspecified-fg"

### ISSUE THREAD

**Issue by titanofold** [dracula/emacs#78]
From the message buffer I have the following error come up a lot.

    Unable to load color "unspecified-fg" [\d+ times]

I see it's referenced 3 times in dracula-theme.el. It appears alongside dracula-bg. I can't tell if unspecified-fg should be dracula-fg or not.

**Comment by milouse** [comment]
No, it’s a weird bug of upstream Emacs I think. `unspecified-bg` must actually work as a color name, from the Emacs docstring itself for exemple: https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/faces.el#L1824

However, from what I can tel, it has no effect at all (works as expected).
