### ISSUE TITLE
On `M-x`  White font color on top of gray background confusing #497

### ISSUE THREAD

**Issue by avatar-lavventura** [dracula/emacs#79]
As you can see white color on top of gray is not readable. Is it possible to change/fix this coloring? Please note that I am using [dracula-theme.](https://draculatheme.com/emacs/)

<img width="289" alt="Screen Shot 2021-03-19 at 16 37 45" src="https://user-images.githubusercontent.com/18537398/111788705-7062d600-88d1-11eb-8e32-fdea959df30b.png">

-------------

my setup:

```
(use-package selectrum
  :hook (after-init . selectrum-mode)
  :config
  (use-package selectrum-prescient
    :custom
    (prescient-filter-method '(literal regexp initialism fuzzy))
    :config
    (selectrum-prescient-mode t)
    (prescient-persist-mode t)))
```

------

I have been told to open this issue here: https://github.com/raxod502/selectrum/issues/497#issuecomment-802990278

**Comment by basil-conto** [comment]
See also: https://emacs.stackexchange.com/q/63980/15748

**Comment by milouse** [comment]
Mmmh very weird. The default value should be black on gray:

![Capture du 2021-03-22 20-32-49](https://user-images.githubusercontent.com/349239/112047640-db204580-8b4d-11eb-953e-d75874334b68.png)

I see in another comment of you that you play with iterm parameters. Can you confirm

- that the problem only occurs in terminal window? (try by opening a graphical emacs window)
- that the problem only occurs with selectrum? (try by using other completion framework like ido or default M-x)

Thanks you very much.

**Comment by avatar-lavventura** [comment]
@milouse Yes sir, please see the paremeters I set, I always set for smart  cursor (sometimes disable and re-able may fix the issue I am having):

<img width="376" alt="image" src="https://user-images.githubusercontent.com/18537398/112213234-eb5c2180-8c2e-11eb-9c29-261465dd56a9.png">

-------

Please see my dracula theme file (I may have done some minor changes): https://github.com/avatar-lavventura/dotfiles/blob/main/dracula-theme.el

- On the terminal window I see the same screenshot you had

On the iTerm changin cursor color to complete white and keeping Cursor Boost at 2 seems like fixed the issue

<img width="147" alt="image" src="https://user-images.githubusercontent.com/18537398/112216247-5824eb00-8c32-11eb-99de-c73b45912e56.png">

**Comment by milouse** [comment]
… So it seems to be an iTerm issue :/ I don’t have a Mac, nor I know this software… I’m afraid I cannot do anything more here. I’m glad you find the correct configuration for iTerm to have it work following your taste.
