### ISSUE TITLE
light is too dark when matching brackets

### ISSUE THREAD

**Issue by kurt-steiner** [dracula/emacs#82]
I found it when matching brackets, though the color shines,but too dark to notice it,  
anymethod to fix it?  
thank you

**Comment by milouse** [comment]
@nesteiner if you still have the issue, could you take some time making a screenshot to better explain what color you find too dark? Thank you very much!

**Comment by milouse** [comment]
Too old without new comment. Closing it. Don’t hesitate to open it again if needed.
