### ISSUE TITLE
The background on tooltips makes them unreadable

### ISSUE THREAD

**Issue by etu** [dracula/emacs#84]
Hi,

I've been using this theme for years, but I'm not sure when this became an issue because I think I've just ignored it for quite some time.

I get a background on tooltips that has the color #fdfdde and a foreground which is #faf8f0 which makes the tooltip unreadable.

See screenshot:
![20211202_15h14m04s_grim](https://user-images.githubusercontent.com/461970/144440489-36be4702-e18d-465c-bdbb-61fe3cda4414.png)

My entire emacs configuration is available here: https://github.com/etu/nixconfig/blob/main/modules/emacs-files/base.el

This theme doesn't seem to set this color, so I'll just assume it's one of the default colors, but I can't find where it comes from.

**Comment by etu** [comment]
From doing some more testing, running this piece of code to override that face works fine:
```elisp
(custom-set-faces
 '(tooltip ((t (:inherit variable-pitch :background "#44475a" :foreground "#f8f8f2")))))
```

I made the customization using `M-x customize-face` and set the colors from `dracula-bg` and `dracula-current` from this projects source code. So I'll just assume that this patch file would just work.

```patch
From 0effbcaf3f4db0a67904c7976cfd13487441f63f Mon Sep 17 00:00:00 2001
From: Elis Hirwing <elis@hirwing.se>
Date: Thu, 2 Dec 2021 15:38:07 +0100
Subject: [PATCH] theme: Add theme colors for tooltip

---
 dracula-theme.el | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/dracula-theme.el b/dracula-theme.el
index 766c22a..25b73b0 100644
--- a/dracula-theme.el
+++ b/dracula-theme.el
@@ -723,6 +723,8 @@ read it before opening a new issue about your will.")
                (term-color-red :foreground ,dracula-red :background ,dracula-red)
                (term-color-white :foreground ,dracula-fg :background ,dracula-fg)
                (term-color-yellow :foreground ,dracula-yellow :background ,dracula-yellow)
+               ;; tooltip
+               (tooltip :foreground ,dracula-fg :background ,dracula-current)
                ;; undo-tree
                (undo-tree-visualizer-current-face :foreground ,dracula-orange)
                (undo-tree-visualizer-default-face :foreground ,fg2)
--
2.33.1
```

**Comment by milouse** [comment]
Thank you very much for your report and testing. Do you mind sending a screenshot of your fix, I’m curious to see the result.

**Comment by etu** [comment]
I'm on another computer now, but I've evalled the custom-set-faces block in my scratch buffer and then triggered a popup in the buffer below here.
![20211202_21h52m30s_grim](https://user-images.githubusercontent.com/461970/144501273-172e4e7c-23b0-40b4-a2c4-db4298aa0c07.png)

**Comment by etu** [comment]
Thanks @milouse! I'm looking forward to the next set of package updates with this patch in it :slightly_smiling_face:

**Comment by milouse** [comment]
Thanks to you for the patch :)
