### ISSUE TITLE
Deprecate master branch in favor of main

### ISSUE THREAD

**Issue by milouse** [dracula/emacs#87]
@zenorocha as I don’t have full admin right over this repository (no problem about that at all), do you mind to change the default branch of this repository to be the `main` one instead of the current `master`?

I’ll check on my side to ensure it won’t break anything downstream in various packaging team.

Thank you very much.

**Comment by milouse** [comment]
Ping @luxonauta maybe?

**Comment by luxonauta** [comment]
Hi 👋🏻 Étienne, I just did it.

Can you add the changes I made to the master to this one as well? 🤔

✅ I've also updated your permissions to administer the repo! Anything can give me a ping!

**Comment by milouse** [comment]
Thank you very much for your reactivity! I’ll merge your change asap.
