### ISSUE TITLE
Fixing minor inconsistencies with markdown mode

### ISSUE THREAD

**Issue by saccarosium** [dracula/emacs#90]
Reading the docs I see some inconsistencies with the current implementation. 

For example: 

- inline code should be green but it's yellow;
- lists should be cyan but  they are gray;
- block quote should be yellow italic but it's purple not italic.

<img width="551" alt="Screenshot 2022-01-16 at 1 44 39 PM" src="https://user-images.githubusercontent.com/96259932/149660422-ad176b23-30a0-4264-a24d-6ec918741c6d.png">

[markdown.txt](https://github.com/dracula/emacs/files/7876945/markdown.txt)

**Comment by milouse** [comment]
Thank you very much for your contribution!
