### ISSUE TITLE
Minor UI fixes

### ISSUE THREAD

**Issue by saccarosium** [dracula/emacs#91]
Hi,
I wanna bring up some inconsistencies between this and the other implementations of the theme.

## Line number

The line number face has the slant italic and for foreground "bg4".  In other editor such as VScode, nvim and atom is not the case.

*Emacs*
<img width="350" alt="Screenshot 2022-01-19 at 4 05 43 PM" src="https://user-images.githubusercontent.com/96259932/150158082-40ab73ea-5a3d-42dd-9534-78975979279d.png">
*Nvim*
<img width="350" alt="Screenshot 2022-01-19 at 4 07 13 PM" src="https://user-images.githubusercontent.com/96259932/150158085-6b7bed3a-20b8-4268-9940-f262a3a979ea.png">
*VScode*
<img width="350" alt="Screenshot 2022-01-19 at 4 07 28 PM" src="https://user-images.githubusercontent.com/96259932/150158088-c1e02d73-0dba-4794-9378-6b13c9cf3c1f.png">
*Atom*
<img width="350" alt="Screenshot 2022-01-19 at 4 07 40 PM" src="https://user-images.githubusercontent.com/96259932/150158091-598a4113-8cae-44da-b4e4-b3240cdddbde.png">

The patch simply removes the italic, makes the foreground "dracula-comment" and makes the background "nil", in case the user want to change the background color to a different one.

```patch
@@ -113,6 +113,8 @@ read it before opening a new issue about your will.")
                (info-string :foreground ,dracula-yellow)
                (lazy-highlight :foreground ,fg2 :background ,bg2)
                (link :foreground ,dracula-cyan :underline t)
+               (linum :foreground ,dracula-comment :background nil)
+               (line-number :inherit linum)
-               (linum :slant italic :foreground ,bg4 :background ,dracula-bg)
-               (line-number :slant italic :foreground ,bg4 :background ,dracula-bg)
                (match :background ,dracula-yellow :foreground ,dracula-bg)
```

## Different colors (only in graphical emacs)

In other implementations usually they are using some colors not listed in the docs such as: "#21222c" and "#191a21".

*VScode*
<img width="450" alt="Screenshot 2022-01-19 at 4 17 09 PM" src="https://user-images.githubusercontent.com/96259932/150160856-f29a80df-f804-4d3f-a66f-af282e38eab6.png">
*Atom*
<img width="450" alt="Screenshot 2022-01-19 at 4 23 49 PM" src="https://user-images.githubusercontent.com/96259932/150161296-2e0fc1f7-2789-4d35-91c3-2f78de757e3a.png">

I think it will be nice implementing this colors in variables such as "contrast" and "unfocus" (the names are only an example).

```patch
@@ -98,7 +98,9 @@ read it before opening a new issue about your will.")
                 (fg2             "#e2e2dc" "#e4e4e4" "brightwhite")
                 (fg3             "#ccccc7" "#c6c6c6" "white")
                 (fg4             "#b6b6b2" "#b2b2b2" "white")
                 (other-blue      "#0189cc" "#0087ff" "brightblue")
+                (contrast        "#191a21")
+                (unfocus         "#21222c"))
```

## Mode-line (Personal taste)

Implementing the different colors contrasts make it so we can ditch the ":box" attribute for distinguishing active and inactive splits, and instead using colors.

*without patch*
<img width="1440" alt="Screenshot 2022-01-19 at 4 53 25 PM" src="https://user-images.githubusercontent.com/96259932/150167364-0fd96bba-58ac-420b-95f5-2c460e54bf1a.png">
*with patch*
<img width="1440" alt="Screenshot 2022-01-19 at 4 55 18 PM" src="https://user-images.githubusercontent.com/96259932/150167374-15100dae-8113-4abe-8b98-7dcb578d016e.png">

```patch 
@@ -543,16 +548,16 @@ read it before opening a new issue about your will.")
                (message-cited-text-4 :foreground ,fg2)
                (message-mml :foreground ,dracula-green :weight normal)
                ;; mode-line
-               (mode-line :background ,dracula-current
-                          :box ,dracula-current :inverse-video nil
+               (mode-line
+                :background ,dracula-current :inverse-video nil
                           ,@(if dracula-alternate-mode-line-and-minibuffer
                                 (list :foreground fg3)
                               (list :foreground dracula-fg)))
                (mode-line-inactive
-                :background ,dracula-bg :inverse-video nil
+                :background ,unfocus :inverse-video nil :box nil
                 ,@(if dracula-alternate-mode-line-and-minibuffer
-                      (list :foreground dracula-comment :box dracula-bg)
-                    (list :foreground fg4 :box bg2)))
+                      (list :foreground dracula-comment)
+                    (list :foreground fg4 )))
```

## Bookmarks

*before the patch*
<img width="80" alt="Screenshot 2022-01-19 at 5 32 37 PM" src="https://user-images.githubusercontent.com/96259932/150173728-b51e3d54-389e-4588-9135-29b7a2427714.png">

*after the patch*
<img width="80" alt="Screenshot 2022-01-19 at 5 33 32 PM" src="https://user-images.githubusercontent.com/96259932/150173879-346aa3bc-ad61-4ac2-bdde-647e2bf12af6.png">

```patch
                (success :foreground ,dracula-green)
                (tooltip :foreground ,dracula-fg :background ,dracula-current)
+               (bookmark-face :background nil :foreground nil)
                (trailing-whitespace :background ,dracula-orange)
                (vertical-border :foreground ,bg2)
```

**Comment by milouse** [comment]
Thanks for your report. I’ll take some time to review it and see what I can/want to do with this different thing.
