### ISSUE TITLE
Dracula theme for Emacs does not customize font-lock-number-face

### ISSUE THREAD

**Issue by josteink** [dracula/emacs#96]
As the title says. 

Once Dracula-theme is activated, font-lock-number-face remains uncustomized. 

This is inconsistent with how this is done ie in the VSCode implementation where numbers receive the same fontification as built in keywords. 

Dracula theme is a great theme, so we should fix this 🙂

**Comment by milouse** [comment]
I may be wrong, but `font-lock-number-face` does not exist https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces-for-Font-Lock.html

Maybe it comes with a specific module? Or are you using a specific version of Emacs (pre-release, spacemacs…)?

**Comment by josteink** [comment]
It's part of Emacs 29, to be released, and used quite consistently in the new tree-sitter based major-modes:

![image](https://user-images.githubusercontent.com/411338/207035614-ed80e7b0-b596-4e72-8574-3c5bf5470aaf.png)

**Comment by milouse** [comment]
Here is the list of new font-lock faces added by the next version:

- `font-lock-escape-face` (inherit `font-lock-regexp-grouping-backslash`, Font Lock mode face used to highlight escape sequences in strings.)
- `font-lock-number-face` (Font Lock mode face used to highlight numbers.)
- `font-lock-operator-face` (Font Lock mode face used to highlight operators.)
- `font-lock-property-face` (inherit `font-lock-variable-name-face`, Font Lock mode face used to highlight properties of an object. For example, the declaration and use of fields in a struct.)
- `font-lock-punctuation-face` (Font Lock mode face used to highlight punctuation characters.)
- `font-lock-bracket-face` (inherit `font-lock-punctuation-face`, Font Lock mode face used to highlight brackets, braces, and parens.)
- `defface font-lock-delimiter-face` (inherit `font-lock-punctuation-face`, Font Lock mode face used to highlight delimiters. What exactly is a delimiter depends on the major mode, but usually these are characters like comma, colon, and semi-colon.)
- `font-lock-misc-punctuation-face` (inherit `font-lock-punctuation-face`, Font Lock mode face used to highlight miscellaneous punctuation.)

**Comment by milouse** [comment]
For the following new faces, I took inspiration [from vscode implementation](https://github.com/dracula/visual-studio-code)

- `font-lock-number-face` will be in purple,
- `font-lock-operator-face` will be in pink

The others are left untouched for now as default value seems ok

**Comment by josteink** [comment]
Awesome. Thanks!
